from . import moron_contributor
from . import moron_service
from . import moron_project
from . import moron_task
from . import moron_contributor_invoice
from . import moron_client_invoice
from . import moron_sale_order
from . import moron_sale_order_line
from . import moron_payment
from . import moron_customer
from . import contributor_service_rate
from . import moron_nationality
from . import ir_ui_menu
